[functions]
  external_node_modules = ["ky-universal", "ky", "core-js", "security-context"]
  node_bundler = "esbuild"
  included_files = ["node_modules/*"]

[dev]
  functionsPort = 5080

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
