[functions]
  external_node_modules = ["ky-universal", "ky", "core-js", "@trustvc/w3c-context", "@trustvc/w3c-vc"]
  node_bundler = "esbuild"

[dev]
  functionsPort = 5080

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
