name: Github Actions

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment: "ci forked"
    if: |
      (!contains(github.event.pull_request.title, '[skip test]') &&
      github.event.pull_request.head.repo.full_name != github.repository)

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install node dependancies
        run: npm ci
      - name: Check Snyk
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Check Prettier
        run: npx prettier --check .
      - name: Lint
        run: npm run lint
      - name: Integration test
        run: npm run test:ci
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
